name: Deploy Attendance System to EC2

on:
  push:
    branches:
      - main  # Pipeline sẽ chạy mỗi khi bạn push code vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/attendance-system
            # Tự động lấy lại quyền sở hữu trước khi Git làm việc
            sudo chown -R ubuntu:ubuntu ~/attendance-system
            
            git reset --hard HEAD
            git fetch origin main
            git reset --hard origin/main
            
            # Build và chạy lại Docker
            sudo docker compose up -d --build